# Generated by Django 3.1 on 2020-12-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empty', max_length=50)),
                ('postData', models.DateField(verbose_name='data publish')),
                ('readCount', models.IntegerField(default=0)),
                ('text', models.FilePathField()),
            ],
            options={
                'verbose_name': 'artical',
                'verbose_name_plural': 'articals',
            },
        ),
    ]
